# GitHub workflow for running automatic linting fixers on your code.
name: Test that lint trap works as expected.

on:
  pull_request:
  workflow_dispatch:

# You should always only be running one job that commits changes at a time.
# Using the git ref as a concurrency flag allows this even with multiple
# workflows that commit.
concurrency: ${{ github.ref }}

# In order to push the changes, the workflow needs permission to write to
# the repository contents.
permissions:
  contents: write

jobs:
  run-action:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        fetch-depth: [0, 1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ matrix.fetch-depth }}
      - uses: ./
        with:
          fix-commands: | 
            echo $(( $(cat .github/run_count.txt) + 1 )) > .github/run_count.txt
          commit-message: "TEST: ${{ matrix.os }}, ${{ matrix.fetch-depth }}"
